[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "leek-core"
version = "1.0.0"
description = "Core quantitative trading engine"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "Proprietary"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "statsmodels",
    "plotly",
    "dash",
    "pymongo",
    "redis",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
]

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ["py313"] 