# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x06\x65ngine\"o\n\rActionRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x11\n\targs_json\x18\x03 \x01(\t\x12\x13\n\x0bkwargs_json\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"Y\n\x0e\x41\x63tionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"l\n\x0c\x45ventMessage\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x11\n\tdata_json\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0e\n\x06source\x18\x05 \x01(\t\"#\n\rListenRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t2\x8e\x01\n\rEngineService\x12>\n\rExecuteAction\x12\x15.engine.ActionRequest\x1a\x16.engine.ActionResponse\x12=\n\x0cListenEvents\x12\x15.engine.ListenRequest\x1a\x14.engine.EventMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONREQUEST']._serialized_start=24
  _globals['_ACTIONREQUEST']._serialized_end=135
  _globals['_ACTIONRESPONSE']._serialized_start=137
  _globals['_ACTIONRESPONSE']._serialized_end=226
  _globals['_EVENTMESSAGE']._serialized_start=228
  _globals['_EVENTMESSAGE']._serialized_end=336
  _globals['_LISTENREQUEST']._serialized_start=338
  _globals['_LISTENREQUEST']._serialized_end=373
  _globals['_ENGINESERVICE']._serialized_start=376
  _globals['_ENGINESERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
